
import {useState,useEffect,useRef,lazy,Suspense} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {places,conditions,makeRoute,totalDistance,type Place} from '../places';
const SceneWorkspace=lazy(()=>import('../SceneWorkspace'));
const PilotAssets=lazy(()=>import('../PilotAssets'));
const StationExperience=lazy(()=>import('../StationExperience'));
import {type PilotAssetId} from '../pilot-data';
import CityExplorer from '../CityExplorer';

type Screen='search'|'confirm'|'routes'|'detail'|'preview';
const labels:Record<string,string>={all:'전체',elevator:'엘리베이터',toilet:'화장실',rest:'쉼터'};
export default function App(){
 const [surface,setSurface]=useState<'city'|'studio'|'legacy'|'pilot'|'station'>(()=>new URLSearchParams(location.search).has('station')?'station':new URLSearchParams(location.search).has('landmarks')?'pilot':'city');
 const [pilotAsset,setPilotAsset]=useState<PilotAssetId>(()=>new URLSearchParams(location.search).has('landmarks')?'tour-hanbit':'station'),[focusPilot,setFocusPilot]=useState<PilotAssetId|undefined>();
 const openPilot=(id:PilotAssetId='station')=>{setPilotAsset(id);if(['station','bakery','metro'].includes(id))setFocusPilot(id);setSurface('pilot');};
 return <Suspense fallback={<div className="map-loading" role="status">3D 화면을 준비하고 있어요…</div>}>
  {surface==='station'?<StationExperience onBack={()=>{setFocusPilot('station');setSurface('city');}}/>:surface==='city'?<CityExplorer initialPilot={focusPilot} onStationExperience={()=>setSurface('station')} onPilotAssets={openPilot} onLegacy={()=>setSurface('legacy')}/>
  :surface==='pilot'?<PilotAssets initial={pilotAsset} onBack={()=>setSurface('city')} onLegacy={()=>setSurface('studio')} onPlace={asset=>{setFocusPilot(asset);setSurface('city');}}/>
  :surface==='studio'?<SceneWorkspace onPlaces={()=>setSurface('city')}/>
  :<><LegacyApp/><button className="back-to-city" onClick={()=>setSurface('city')}>← 대전 전체 지도로 돌아가기</button></>}
 </Suspense>;
}
function LegacyApp(){
 const [survey,setSurvey]=useState(true),[prefs,setPrefs]=useState<string[]>([]),[screen,setScreen]=useState<Screen>('search'),[selected,setSelected]=useState<Place>(places[1]);
 const [from,setFrom]=useState('plaza'),[to,setTo]=useState('arboretum'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[via,setVia]=useState(false);
 const [geo,setGeo]=useState(false),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[playing,setPlaying]=useState(false),[progress,setProgress]=useState(0),[motion,setMotion]=useState(true),[notice,setNotice]=useState(''),[sheet,setSheet]=useState(true),[mode,setMode]=useState('walk');
 const drag=useRef<{x:number;y:number;px:number;py:number}|null>(null);
 const route=makeRoute(from,to,via),meters=Math.round(totalDistance(route)),stay=route.reduce((n,p)=>n+p.duration,0)+(prefs.includes('자주 쉬어가기')?15:0);
 const shown=places.filter(p=>(p.name.includes(query.trim())||p.category.includes(query.trim()))&&(filter==='all'||p.facility.includes(filter)));
 const point=(p:Place)=>geo?{x:180+(p.lon-127.3857)*200000,y:530-(p.lat-36.3669)*180000}:{x:p.x,y:p.y};
 const path=route.map((p,i)=>{const pt=point(p);return (i?'L':'M')+pt.x+','+pt.y}).join(' ');
 const idx=Math.min(Math.floor(progress/100*Math.max(1,route.length-1)),route.length-1),current=route[idx],a=current?point(current):{x:640,y:450},b=route.length?point(route[Math.min(idx+1,route.length-1)]):a;
 const fraction=(progress/100*Math.max(1,route.length-1))%1,traveler={x:a.x+(b.x-a.x)*fraction,y:a.y+(b.y-a.y)*fraction};
 useEffect(()=>{const mq=window.matchMedia('(prefers-reduced-motion: reduce)');const fn=()=>setMotion(!mq.matches);fn();mq.addEventListener('change',fn);return()=>mq.removeEventListener('change',fn)},[]);
 useEffect(()=>{if(!playing)return;const id=window.setInterval(()=>setProgress(p=>Math.min(100,p+.4)),80);return()=>window.clearInterval(id)},[playing]);
 useEffect(()=>{if(progress>=100)setPlaying(false)},[progress]);
 useEffect(()=>{if(!notice)return;const id=window.setTimeout(()=>setNotice(''),4500);return()=>window.clearTimeout(id)},[notice]);
 function open(p:Place){setSelected(p);setScreen('detail');setSheet(true);setPlaying(false)}
 function searchRoute(){if(from===to){setNotice('출발지와 도착지를 다르게 선택해 주세요.');return}setScreen('confirm');setFilter('all');setQuery('');setProgress(0);setPlaying(false);setSheet(true)}
 function toggle(p:string){setPrefs(v=>v.includes(p)?v.filter(x=>x!==p):[...v,p])}
 function resetView(){setPan({x:0,y:0});setZoom(1)}
 const routeVisible=['confirm','routes','preview'].includes(screen);
 return <div className={'app '+(!motion?'still':'')}>
 <header className="topbar"><a className="brand" href="/"><img src="/brand/mark-128.png" alt=""/><strong>갈수있슈<span>나에게 맞는 대전 여행길</span></strong></a><div className="region"><i className="live-dot"/>대전광역시 <span>/</span> 한밭수목원 일대</div><button className="profile" onClick={()=>setSurvey(true)}>♿ <span>나의 이동 조건</span><b>{prefs.length||'+'}</b></button></header>
 <main className="workspace"><nav className="rail" aria-label="메인 메뉴"><button className={screen==='search'?'active':''} onClick={()=>{setScreen('search');setSheet(true);setPlaying(false)}}><span>◈</span>지도</button><button className={routeVisible?'active':''} onClick={searchRoute}><span>⌁</span>길찾기</button><button onClick={()=>setSurvey(true)}><span>☷</span>이동 조건</button><small className="rail-bottom">DAEJEON WITH YOU</small></nav>
 <aside className={'sidebar '+(!sheet?'collapsed':'')} aria-label="여행 계획"><button className="sheet-handle" aria-label={sheet?'패널 접기':'패널 펼치기'} onClick={()=>setSheet(!sheet)}><span/></button><div className="side-scroll">
 {screen==='search'&&<><div className="heading"><span className="eyebrow">함께 가는 대전</span><h1>어디로 가볼까유?</h1><p>내게 필요한 정보를 먼저 살펴보세요.</p></div><div className="search-field"><span>⌕</span><input aria-label="장소 검색" placeholder="장소, 공원, 미술관 검색" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="검색어 지우기" onClick={()=>setQuery('')}>×</button>}</div>
 <div className="endpoint-fields"><label><i className="dot start"/>출발<select aria-label="출발지" value={from} onChange={e=>setFrom(e.target.value)}>{places.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="swap" aria-label="출발 도착 바꾸기" onClick={()=>{setFrom(to);setTo(from)}}>⇅</button><label><i className="dot finish"/>도착<select aria-label="도착지" value={to} onChange={e=>setTo(e.target.value)}>{places.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>
 <button className="find-route" onClick={searchRoute}>내 조건으로 길 살펴보기 <span>→</span></button><div className="section-title"><h2>오늘, 이곳은 어때요?</h2><span>{shown.length}개 장소</span></div>{shown.map(p=><button className="place-row" key={p.id} onClick={()=>open(p)}><img src={p.image} alt={p.short+' 풍경'}/><span><small>{p.category}</small><strong>{p.short}</strong><em>{p.facility.includes('toilet')?'장애인 화장실 안내':'광장 접근성 안내'}</em></span><b>→</b></button>)}{!shown.length&&<div className="empty"><h3>아직 찾지 못했어요.</h3><p>현재 한밭수목원 주변 3곳을 살펴볼 수 있어요.</p><button onClick={()=>{setQuery('');setFilter('all')}}>전체 장소 보기</button></div>}<p className="little-note">ⓘ 시설의 존재와 오늘 이용할 수 있는지는 달라요.<br/>출발 전 운영 상태를 확인해 주세요.</p></>}
 {screen==='confirm'&&<><button className="back" onClick={()=>setScreen('search')}>← 검색으로</button><div className="heading"><span className="eyebrow">01 · 출발과 도착</span><h1>이곳에서 출발하나요?</h1><p>지도 위 두 지점을 확인해 주세요.</p></div>{route.filter((_,i)=>i===0||i===route.length-1).map((p,i)=><div className="confirm-place" key={p.id}><span className={'number '+(!i?'navy':'coral')}>{i?'도착':'출발'}</span><h2>{p.name}</h2><p>{p.category}</p><small>{p.lat.toFixed(5)}, {p.lon.toFixed(5)}</small></div>)}<div className="caution"><b>출입구 확인이 필요해요</b><p>표시 지점은 장소 대표 좌표예요. 휠체어 진입 가능한 실제 출입구 위치는 방문 전 확인해 주세요.</p></div><button className="find-route" onClick={()=>setScreen('routes')}>맞아요, 동선 살펴보기 →</button></>}
 {screen==='routes'&&<><button className="back" onClick={()=>setScreen('confirm')}>← 출발·도착 확인</button><div className="heading"><span className="eyebrow">02 · 나에게 맞는 동선</span><h1>가기 전에, 한 번 더.</h1><p>{places.find(p=>p.id===from)?.short} → {places.find(p=>p.id===to)?.short}</p></div><div className="condition-summary"><span>{prefs.length?prefs.slice(0,3).join(' · '):'이동 조건에 따라 확인 항목이 달라져요.'}</span><button onClick={()=>setSurvey(true)}>수정</button></div>
 <div className="transport-tabs" role="group" aria-label="이동 방법">{[['walk','도보·휠체어'],['subway','지하철'],['taxi','택시']].map(([v,l])=><button key={v} aria-pressed={mode===v} className={mode===v?'active':''} onClick={()=>setMode(v)}>{l}</button>)}</div>
 {mode!=='walk'?<div className="caution"><b>{mode==='subway'?'지하철 접근 동선 미확인':'차량 탑승 조건 확인 필요'}</b><p>{mode==='subway'?'역 출입구와 엘리베이터 연결 정보를 확보하지 못했어요. 현재 지하철 경로를 제공하지 않아요.':'휠체어 탑승 가능 차량과 배차 시간이 연동되어 있지 않아요. 차량 탑승 조건을 직접 확인해 주세요.'}</p><button onClick={()=>setMode('walk')}>도보·휠체어 동선 보기</button></div>:<>{[false,true].map(v=><button key={String(v)} className={'route-card '+(via===v?'selected':'')} aria-pressed={via===v} onClick={()=>{setVia(v);setProgress(0)}}><span className="route-card-top"><b>{v?'한 곳 더 둘러보기':'출발 · 도착 바로 연결'}</b><i className="radio"/></span><span className="metric">{Math.round(totalDistance(makeRoute(from,to,v)))}<small>m · 대표 지점 간 직선 합계</small></span><span className="route-stops">{makeRoute(from,to,v).map(p=>p.short).join(' → ')}</span><span className="route-foot">동선 미리보기 · 실제 보행 경로 아님</span></button>)}<div className="section-title"><h2>내 조건으로 확인할 것</h2></div><ul className="checklist">{(prefs.length?prefs:['계단 피하기','화장실 먼저 확인']).map(p=><li key={p}><span>!</span><div><b>{p}</b><p>{p.includes('화장실')?'운영 시간과 출입문 폭을 확인해 주세요.':p.includes('쉬어')?'휴식 15분을 추가했어요. 쉼터 위치는 현장 확인이 필요해요.':p.includes('시각')?'음성·점자 안내와 점자블록 연결 상태를 확인해 주세요.':p.includes('청각')?'현장 문자 안내와 비상 시 시각 알림을 확인해 주세요.':'구간별 턱, 경사와 통과 폭은 아직 확인되지 않았어요.'}</p></div></li>)}</ul><button className="find-route" onClick={()=>{setScreen('preview');setProgress(0);setPlaying(false)}}>동선 미리보기 →</button></>}</>}
 {screen==='detail'&&<><button className="back" onClick={()=>setScreen('search')}>← 장소 목록</button><figure className="detail-image"><img src={selected.image} alt={selected.name+' 장소 사진'}/><figcaption>한국관광공사 공개 관광정보</figcaption></figure><div className="heading"><span className="eyebrow">{selected.category}</span><h1>{selected.name}</h1><p>머무는 시간 약 {selected.duration}분 · 계획용 추정</p></div><div className="destination-actions"><button onClick={()=>{setFrom(selected.id);setScreen('search');setNotice('출발지로 설정했어요.')}}>출발로 설정</button><button onClick={()=>{setTo(selected.id);setScreen('search');setNotice('도착지로 설정했어요.')}}>도착으로 설정</button></div><h2 className="detail-heading">공개 자료에 안내된 시설</h2><ul className="access-list">{selected.access.map(t=><li key={t}><span>✓</span>{t}</li>)}</ul><div className="caution"><b>아직 확인되지 않았어요</b><p>{selected.unknown}</p></div><dl className="detail-facts"><div><dt>운영 안내</dt><dd>{selected.hours}</dd></div><div><dt>대표 좌표</dt><dd>{selected.lat.toFixed(6)}, {selected.lon.toFixed(6)}<small>출입구 좌표가 아니에요.</small></dd></div><div><dt>자료 확인</dt><dd>2026.09.13<small>당일 운영 상태는 실시간 정보가 아니에요.</small></dd></div></dl><div className="source-actions"><a href={selected.source} target="_blank" rel="noreferrer">한국관광공사 원문 ↗</a><a href={'tel:'+selected.phone}>전화로 문의 ↗</a></div></>}
 {screen==='preview'&&<><button className="back" onClick={()=>{setScreen('routes');setPlaying(false)}}>← 동선 비교</button><div className="heading"><span className="eyebrow">03 · 여행 미리보기</span><h1>내 속도로, 함께 가유.</h1><p>캐릭터를 따라 방문 순서를 살펴보세요.</p></div><div className="preview-summary"><div><b>{meters}<small>m</small></b><span>지점 간 직선 합계</span></div><div><b>{stay}<small>분</small></b><span>체류·휴식 예상 합계</span></div></div><p className="quiet">실제 이동 거리·이동 시간은 경로 데이터 확인 후 제공됩니다.</p><div className="timeline">{route.map((p,i)=><button key={p.id} className={current?.id===p.id?'current':''} onClick={()=>{setProgress(i/(route.length-1)*100);setPlaying(false);setSelected(p)}}><span>{i+1}</span><div><b>{p.short}</b><small>{p.duration}분 머무르기 · 예상</small></div>{current?.id===p.id&&<em>현재 단계</em>}</button>)}</div><label className="progress-label">동선 진행 <span>{Math.round(progress)}%</span><input aria-label="미리보기 진행 위치" type="range" min="0" max="100" value={progress} onChange={e=>{setProgress(+e.target.value);setPlaying(false)}}/></label><button className="preview-play" onClick={()=>{if(progress>=100)setProgress(0);setPlaying(!playing)}}>{playing?'Ⅱ 일시정지':'▷ 동선 재생'}</button><button className="detail-link" onClick={()=>current&&open(current)}>현재 장소 시설 확인 →</button><div className="caution"><b>길 안내가 아닌 미리보기예요</b><p>실시간 위치를 추적하지 않아요. 선은 방문 순서만 보여주며 실제 통행 가능성을 보장하지 않아요.</p></div></>}
 </div><footer className="sidebar-footer"><i className="live-dot"/> 대전 시범 지역 <span>함께라서, 갈수있슈.</span></footer></aside>
 <section className={'map '+(geo?'geo':'')} aria-label="인터랙티브 여행 지도"><div className="map-toolbar"><div className="layers">{Object.entries(labels).map(([k,l])=><button className={filter===k?'active':''} aria-pressed={filter===k} key={k} onClick={()=>{setFilter(k);setScreen('search');setPlaying(false)}}>{l}</button>)}</div><button className="map-type" onClick={()=>{setGeo(!geo);resetView()}}>{geo?'미니어처 보기':'실제 위치 관계'}</button></div>
 <div className="map-viewport" tabIndex={0} aria-label="지도를 드래그하거나 방향키로 이동하세요" onKeyDown={e=>{const dirs:Record<string,number[]>={ArrowLeft:[40,0],ArrowRight:[-40,0],ArrowUp:[0,40],ArrowDown:[0,-40]};if(dirs[e.key]){e.preventDefault();setPan(p=>({x:p.x+dirs[e.key][0],y:p.y+dirs[e.key][1]}))}}} onWheel={e=>setZoom(z=>Math.max(.7,Math.min(2.5,z-e.deltaY*.001)))} onPointerDown={e=>{if((e.target as Element).closest('button'))return;drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current)setPan({x:Math.max(-800,Math.min(800,drag.current.px+e.clientX-drag.current.x)),y:Math.max(-500,Math.min(500,drag.current.py+e.clientY-drag.current.y))})}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
 <div className="map-world" style={{transform:'translate('+pan.x+'px,'+pan.y+'px) scale('+zoom+')'}}>{!geo&&<img className="city-image" src="/assets/world.webp" alt="대전 미니어처 도시. 실제 지형과 다를 수 있는 탐색용 일러스트." draggable={false}/>} {geo&&<div className="geo-ground"><span className="north">N ↑</span><div className="geo-caption">대전 · 둔산대로 일대<br/><small>대표 좌표를 기준으로 배치한 위치 관계도</small></div></div>}
 <svg viewBox="0 0 1000 700" className="route-svg" aria-hidden="true">{routeVisible&&<><path d={path} stroke="white" strokeWidth="12" fill="none" strokeLinejoin="round"/><path d={path} className={'route-line '+(playing?'running':'')} strokeWidth="6" fill="none" strokeLinecap="round" strokeLinejoin="round" strokeDasharray="9 9"/></>}</svg>
 {shown.map(p=>{const pt=point(p);return <button key={p.id} className={'map-pin '+(selected.id===p.id&&screen==='detail'?'selected':'')} style={{left:pt.x/10+'%',top:pt.y/7+'%'}} onClick={()=>open(p)}><span className="pin-icon"><span>{p.id===from&&routeVisible?'출발':p.id===to&&routeVisible?'도착':p.id==='arboretum'?'♧':p.id==='museum'?'▥':'◈'}</span></span><b>{p.short}</b>{filter!=='all'&&<small>시설 위치는 현장 확인</small>}</button>})}
 {screen==='preview'&&<div className="traveler" style={{left:traveler.x/10+'%',top:traveler.y/7+'%'}}><img src="/assets/traveler.webp" alt="동선 미리보기 캐릭터"/><span>나의 여행</span></div>}{!geo&&<><img className="city-bus ambient" src="/assets/bus.webp" alt="" aria-hidden="true"/><img className="city-person ambient" src="/assets/traveler.webp" alt="" aria-hidden="true"/></>}</div></div>
 <div className="map-tools"><button aria-label="지도 확대" onClick={()=>setZoom(z=>Math.min(2.5,z+.2))}>＋</button><button aria-label="지도 축소" onClick={()=>setZoom(z=>Math.max(.7,z-.2))}>−</button><button aria-label="지도 위치 초기화" onClick={resetView}>⌖</button><button aria-label={motion?'도시 움직임 끄기':'도시 움직임 켜기'} aria-pressed={motion} onClick={()=>setMotion(!motion)}>{motion?'Ⅱ':'▷'}</button></div><div className="map-caption"><span>{geo?'대표 좌표 관계도':'미니어처 탐색 지도'}</span><small>{geo?'정밀 보행 지도가 아니에요':'지형·시설 배치는 일러스트예요'}</small></div><div className="map-legend"><span><i className="green"/>공개 시설 안내</span><span><i className="yellow"/>운영 확인 필요</span>{routeVisible&&<span><i className="coral"/>방문 순서</span>}</div><button className="mobile-open" onClick={()=>setSheet(!sheet)}>{sheet?'지도를 더 크게 ↑':'여행 계획 펼치기 ↑'}</button></section></main>
 <Dialog.Root open={survey} onOpenChange={setSurvey}><Dialog.Portal><Dialog.Overlay className="survey-overlay"/><Dialog.Content className="survey-dialog"><div className="survey-visual"><img src="/assets/welcome.webp" alt="다양한 이동 조건의 여행자가 함께하는 미니어처 거리"/><div><span>모두의 발걸음이<br/>여행이 되는 곳.</span><small>대전에서 시작하는 나다운 여행</small></div></div><div className="survey-content"><Dialog.Close className="survey-close" aria-label="설문 닫기">×</Dialog.Close><span className="eyebrow">반가워유, 갈수있슈예요.</span><Dialog.Title>어떤 길이<br/>더 편하신가요?</Dialog.Title><Dialog.Description>이동할 때 필요한 조건을 알려주세요.<br/>여러 개를 선택하고, 언제든 바꿀 수 있어요.</Dialog.Description><div className="condition-grid">{conditions.map((p,i)=><button key={p} aria-pressed={prefs.includes(p)} className={prefs.includes(p)?'chosen':''} onClick={()=>toggle(p)}><span>{['♿','↗','⌁','♧','WC','♡','◉','◌'][i]}</span>{p}<i>{prefs.includes(p)?'✓':'+'}</i></button>)}</div><p className="privacy-note">선택한 조건은 이번 이용 중에만 반영해요.</p><button className="survey-start" onClick={()=>setSurvey(false)}>나에게 맞는 지도 보기 <span>→</span></button><button className="skip" onClick={()=>{setPrefs([]);setSurvey(false)}}>지금은 건너뛰기</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>{notice&&<div className="toast" role="status">{notice}</div>}</div>
}
