import {forwardRef,useEffect,useImperativeHandle,useRef,useState} from 'react';
import {type CityPlace,type Coordinate,placeCoordinate} from './city-data';
import {chooseMapPins} from './map-pins';
import type {RouteResult} from './route-engine';
export type CityViewHandle={fly:(p:Coordinate,zoom?:number,inset?:number)=>void;overview:()=>void;zoom:(factor:number)=>void;tilt:()=>void;fitRoute:(coords:Coordinate[])=>void};
type Props={transitGeometry?:GeoJSON.FeatureCollection<GeoJSON.LineString>|null;transitSimulation?:import('./transit-types').TransitSimulation|null;focusedPins?:boolean;places:CityPlace[];selected:string;from:CityPlace|null;to:CityPlace|null;route:RouteResult|null;onPick:(p:CityPlace)=>void;onPoint:(p:Coordinate)=>void};
const origin=[127.395,36.34];const project=(c:number[])=>[(c[0]-origin[0])*89700,-(c[1]-origin[1])*111320];const unproject=(c:number[]):Coordinate=>[c[0]/89700+origin[0],origin[1]-c[1]/111320];
export const CityFallback=forwardRef<CityViewHandle,Props>(function CityFallback(props,ref){
 const [data,setData]=useState<Record<string,GeoJSON.FeatureCollection>|null>(null),[error,setError]=useState(false),[attempt,setAttempt]=useState(0),[view,setView]=useState({x:0,y:0,w:38000});const el=useRef<SVGSVGElement>(null),drag=useRef<{x:number;y:number;vx:number;vy:number}|null>(null);
 useEffect(()=>{const controller=new AbortController();let stopped=false;setError(false);fetch('/data/overview.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(value=>{if(!stopped)setData(value);}).catch(cause=>{if(!stopped&&cause?.name!=='AbortError')setError(true);});return()=>{stopped=true;controller.abort();};},[attempt]);
 useImperativeHandle(ref,()=>({fly:(p,zoom=15)=>{const [x,y]=project(p);setView({x,y,w:Math.max(700,4500*2**(15-zoom))});},overview:()=>setView({x:0,y:0,w:38000}),zoom:f=>setView(v=>({...v,w:Math.max(400,Math.min(65000,v.w/f))})),tilt:()=>{},fitRoute:coords=>{const pts=coords.map(project),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);setView({x:(Math.min(...xs)+Math.max(...xs))/2,y:(Math.min(...ys)+Math.max(...ys))/2,w:Math.max(1000,Math.max(Math.max(...xs)-Math.min(...xs),Math.max(...ys)-Math.min(...ys))*1.5)});}}),[]);
 const path=(g:GeoJSON.Geometry):string=>{if(g.type==='LineString')return g.coordinates.map((c,i)=>(i?'L':'M')+project(c).join(',')).join(' ');if(g.type==='MultiLineString')return g.coordinates.map(c=>path({type:'LineString',coordinates:c})).join(' ');if(g.type==='Polygon')return g.coordinates.map(c=>path({type:'LineString',coordinates:c})+'Z').join(' ');if(g.type==='MultiPolygon')return g.coordinates.map(c=>path({type:'Polygon',coordinates:c})).join(' ');return '';};
 const scale=view.w/900;const pins=chooseMapPins(props.places,{selected:props.selected,from:props.from,to:props.to,focused:!!props.focusedPins,route:!!props.route||!!props.transitSimulation,zoom:view.w>10000?12:16,width:900,height:810,project:p=>{const [x,y]=project(placeCoordinate(p));return {x:(x-view.x)/scale+450,y:(y-view.y)/scale+405};},contains:p=>{const [x,y]=project(placeCoordinate(p));return Math.abs(x-view.x)<view.w/2&&Math.abs(y-view.y)<view.w*.45;}});for(const p of [props.from,props.to])if(p&&!pins.find(x=>x.id===p.id))pins.push(p);
 return <div className="city-fallback"><svg ref={el} role="img" aria-label="대전 실제 지형 2D 호환 지도" viewBox={`${view.x-view.w/2} ${view.y-view.w*.45} ${view.w} ${view.w*.9}`} onWheel={e=>setView(v=>({...v,w:Math.max(400,Math.min(65000,v.w*(e.deltaY>0?1.12:.88)))}))} onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY,vx:view.x,vy:view.y};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current||!el.current)return;const ratio=view.w/el.current.getBoundingClientRect().width;setView(v=>({...v,x:drag.current!.vx-(e.clientX-drag.current!.x)*ratio,y:drag.current!.vy-(e.clientY-drag.current!.y)*ratio}));}} onPointerUp={e=>{if(drag.current&&Math.hypot(e.clientX-drag.current.x,e.clientY-drag.current.y)<4&&el.current){const ctm=el.current.getScreenCTM();if(ctm){const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(ctm.inverse());props.onPoint(unproject([p.x,p.y]));}}drag.current=null;}} onPointerCancel={()=>drag.current=null}>
 <rect x={-60000} y={-60000} width={120000} height={120000} fill="#f3f2e9"/>
 {(['park','water','waterway','road','boundary'] as const).map(kind=><g key={kind} fill={kind==='park'?'#cfdebb':kind==='water'?'#a9d4d4':'none'} stroke={kind==='waterway'?'#9ccacc':kind==='road'?'#fff':kind==='boundary'?'#81a18e':'none'} strokeWidth={kind==='boundary'?1.3*scale:kind==='road'?3*scale:2*scale} strokeDasharray={kind==='boundary'?`${6*scale} ${5*scale}`:undefined}>{data?.[kind]?.features.map(f=><path key={f.id} d={path(f.geometry)}/>)}</g>)}
 {props.transitGeometry?.features.map((f,i)=><path key={'transit-'+i} d={path(f.geometry)} fill="none" stroke={f.properties?.mode==='subway'?'#7855b7':f.properties?.mode==='walk'?'#a66a55':'#267ba3'} strokeWidth={(f.properties?.mode==='walk'?4:5)*scale} strokeDasharray={f.properties?.mode==='walk'?`${4*scale} ${4*scale}`:undefined}/>)}
 {props.route&&<><path d={path({type:'LineString',coordinates:props.route.coordinates})} fill="none" stroke="#fff" strokeWidth={8*scale}/><path d={path({type:'LineString',coordinates:props.route.coordinates})} fill="none" stroke="#dc7654" strokeWidth={4*scale}/>{props.route.connectors.map((c,i)=><path key={i} d={path({type:'LineString',coordinates:c})} fill="none" stroke="#a97f62" strokeWidth={3*scale} strokeDasharray={`${4*scale} ${4*scale}`}/>)}</>}
 {pins.map(p=>{const [x,y]=project(placeCoordinate(p)),selected=p.id===props.selected;return <g key={p.id} transform={`translate(${x} ${y})`} role="button" aria-label={p.name} tabIndex={0} className="fallback-pin" onPointerDown={e=>e.stopPropagation()} onPointerUp={e=>{e.stopPropagation();props.onPick(p);}} onKeyDown={e=>{if(e.key==='Enter')props.onPick(p);}}><circle r={(selected?8:5)*scale} fill={p.id===props.from?.id?'#4b8374':p.id===props.to?.id?'#d97958':'#75957b'} stroke="white" strokeWidth={2*scale}/>{(selected||p.id===props.from?.id||p.id===props.to?.id)&&<text y={-12*scale} textAnchor="middle" fontSize={14*scale} fill="#263e37" paintOrder="stroke" stroke="white" strokeWidth={4*scale}>{p.name}</text>}</g>;})}
 </svg><div className="compat-label">2D 호환 지도 <span>이 브라우저에서 3D 그래픽을 사용할 수 없어요.</span></div>{!data&&<div className="map-loading">{error?'지도 데이터를 불러오지 못했어요.':'대전 지도를 불러오는 중이에요…'}{error&&<button className="dj-route-button" style={{width:'auto'}} onClick={()=>setAttempt(n=>n+1)}>다시 불러오기</button>}</div>}</div>;
});
