import {useMemo,useState,useId} from 'react';
import {formatDistance} from './city-data';
import {slopeSummary} from './slope-summary';
import type {RouteResult} from './route-engine';
export function JourneyPlayer({route,playing,progress,speed,follow,onPlaying,onSeek,onSpeed,onFollow,onDetails}:{route:RouteResult;playing:boolean;progress:number;speed:number;follow:boolean;onPlaying:(v:boolean)=>void;onSeek:(v:number)=>void;onSpeed:(v:number)=>void;onFollow:(v:boolean)=>void;onDetails:()=>void}){
 const [collapsed,setCollapsed]=useState(false);const detailsId=useId();
 const togglePlay=()=>{if(progress>=1)onSeek(0);onPlaying(!playing);};
 const section=route.sections?.find(s=>route.distance*progress>=s.startDistance&&route.distance*progress<=s.startDistance+s.distance);
 const slope=route.elevation?.segments.find(s=>route.distance*progress>=s.start&&route.distance*progress<=s.end);
 const runs=useMemo(()=>slopeSummary(route),[route]);
 const run=runs.find(s=>route.distance*progress>=s.start&&route.distance*progress<=s.end);
 const remaining=run?Math.max(0,run.end-route.distance*progress):0;
 const names={steps:'계단',rough:'거친 노면',steep:'급경사',bridge:'다리'};
 return <div className={'journey-player'+(collapsed?' is-collapsed':'')}><div className="journey-heading"><span className="journey-live"/><strong>{progress>=1?'도착 지점에 도달했어요':playing?'여행길을 따라가는 중':'출발 전에 동선을 둘러보세요'}</strong>{collapsed&&<><span className="journey-mini-progress" aria-label="진행률">{Math.round(progress*100)}%</span><select className="journey-mini-speed" aria-label="시연 재생 속도" value={speed} onChange={e=>onSpeed(Number(e.target.value))}><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select><button className="journey-mini-follow" aria-pressed={follow} aria-label={'카메라 따라가기 '+(follow?'켬':'끔')} onClick={()=>onFollow(!follow)}>⌖</button><button className="journey-mini-play" aria-label={playing?'시뮬레이션 일시정지':'시뮬레이션 재생'} onClick={togglePlay}>{playing?'Ⅱ':'▶'}</button></>}<button className="journey-collapse" aria-expanded={!collapsed} aria-controls={detailsId} aria-label={collapsed?'시뮬레이션 창 펼치기':'시뮬레이션 창 접기'} onClick={()=>setCollapsed(v=>!v)}>{collapsed?'펼치기 ⌃':'접기 ⌄'}</button></div><div id={detailsId} className="journey-expandable" inert={collapsed} aria-hidden={collapsed}><div className="journey-expandable-inner"><button className="journey-detail-link" onClick={onDetails}>경로 상세 ↗</button><div className="journey-timeline"><input aria-label="동선 미리보기 진행 위치" type="range" min="0" max="1000" value={Math.round(progress*1000)} onChange={e=>onSeek(Number(e.target.value)/1000)}/><div><span>{formatDistance(route.distance*progress)} 이동</span><b>{Math.round(progress*100)}%</b><span>전체 {formatDistance(route.distance)}</span></div></div><div className="journey-controls"><button aria-label="처음으로" onClick={()=>{onSeek(0);onPlaying(false);}}>↺</button><button className="journey-play" onClick={togglePlay}>{playing?'Ⅱ 일시정지':progress>=1?'▶ 다시 보기':'▶ 미리보기'}</button><select aria-label="시연 재생 속도" value={speed} onChange={e=>onSpeed(Number(e.target.value))}><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select><button aria-pressed={follow} onClick={()=>onFollow(!follow)}>따라가기 {follow?'켬':'끔'}</button></div>{run&&(run.kind==='up'||run.kind==='down')&&<p><b>{run.kind==='up'?'오르막':'내리막'} 남은 거리 {formatDistance(remaining)} · 약 {Math.max(1,Math.ceil(remaining/Math.max(1,route.distance+route.connectorDistance)*route.minutes))}분</b> · 높이 변화 약 {Math.round(remaining*Math.abs(run.grade??0)/100)}m · 추정</p>}<p>{section?'이 구간: '+section.kinds.map(k=>names[k]).join(' · ')+' · 통행 조건을 확인해 주세요.':slope?.grade!=null?`${slope.kind==='up'?'↗ 오르막':slope.kind==='down'?'↘ 내리막':'— 높이 변화 적음'} · 약 ${Math.abs(slope.grade).toFixed(1)}% · 지형 추정`:'실제 현재 위치가 아닌 동선 시연이에요. 경사는 미확인이에요.'}</p></div></div></div>;
}
