import {useEffect,useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import type {AccessCoverage,Mobility} from './city-data';
const choices=[{key:'wheelchair',image:'wheelchair',title:'휠체어·유아차로 이동해요',copy:'휠체어 불가로 등록된 길을 제외해요.'},{key:'steps',image:'ramp',title:'계단 없는 길이 좋아요',copy:'계단으로 등록된 구간을 제외해요.'},{key:'rest',image:'rest',title:'중간중간 쉬고 싶어요',copy:'경로와 도착지 주변 쉼터를 함께 봐요.'}] as const;
export function MobilitySurvey({open,onOpenChange,value,onSave,coverage}:{open:boolean;onOpenChange:(v:boolean)=>void;value:Mobility;onSave:(p:Mobility)=>void;coverage:AccessCoverage|null}){
 const [draft,setDraft]=useState(value),[step,setStep]=useState(0);
 // The opening step is the reason this app exists, so it only appears once the numbers behind it
 // are loaded. Without them the survey starts where it always did.
 const steps=coverage?3:2,offset=coverage?1:0;
 useEffect(()=>{if(open){setDraft(value);setStep(0);}},[open]);
 return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="dj-survey-overlay"/><Dialog.Content className="mobility-survey"><Dialog.Close className="dj-survey-close" aria-label="설문 닫기">×</Dialog.Close><div className="survey-content"><span className="survey-step">{coverage&&step===0?'갈수있슈가 시작된 이유':'나에게 맞는 여행 준비'} · {step+1} / {steps}</span><Dialog.Title>{coverage&&step===0?'대전의 길은 아직 기록되지 않았어요':step===offset?'어떤 길이 더 편하신가요?':'조금 더 편한 길을 골라요'}</Dialog.Title><Dialog.Description>{coverage&&step===0?'우리가 수집한 대전 전역 자료를 세어 본 결과예요.':step===offset?'해당하는 항목을 모두 골라 주세요. 나중에 바꿀 수 있어요.':'노면과 경사에 대한 선호를 반영해요.'}</Dialog.Description>
 {coverage&&step===0?<div className="survey-evidence"><div className="survey-figure"><b>{Math.round(coverage.documented/coverage.places*1000)/10}<i>%</i></b><span>대전에 기록된 장소 <strong>{coverage.places.toLocaleString()}곳</strong> 중 휠체어 접근성이 표기된 곳은 <strong>{coverage.documented.toLocaleString()}곳</strong>뿐이에요.</span></div><ul className="survey-gaps"><li><b>{coverage.toiletsDocumented}</b><span>공개 화장실 {coverage.toilets}곳 중 휠체어 화장실로 확인된 곳</span></li><li><b>{coverage.elevators}</b><span>엘리베이터로 기록된 지점</span></li></ul><p className="survey-evidence-note">그래서 갈수있슈는 <strong>갈 수 있다고 단정하지 않아요.</strong> 아는 것은 출처와 함께, 모르는 것은 모른다고 보여드려요. 남은 두 단계에서 나에게 맞는 길의 조건을 골라 주세요.</p><small>OpenStreetMap 대전 스냅샷 {coverage.snapshot.slice(0,10)} 기준으로 계산했어요.</small></div>:step===offset?<div className="survey-cards">{choices.map(c=><button key={c.key} type="button" aria-pressed={draft[c.key]} onClick={()=>setDraft(p=>({...p,[c.key]:!p[c.key]}))}><span className="survey-check" aria-hidden="true">{draft[c.key]?'✓':'+'}</span><img src={'/assets/survey/'+c.image+'.webp'} alt=""/><strong>{c.title}</strong><small>{c.copy}</small></button>)}</div>:<div className="survey-refine">{([['steep','가파른 경사를 피할게요','경사 5% 초과로 기록된 구간 제외'],['rough','매끄러운 길이 좋아요','자갈·흙·모래로 기록된 길 제외']] as const).map(([key,label,help])=><label key={key}><input type="checkbox" checked={draft[key]} onChange={e=>setDraft(p=>({...p,[key]:e.target.checked}))}/><span><strong>{label}</strong><small>{help}</small></span></label>)}<div className="survey-note"><strong>모르는 정보는 모른다고 알려드려요.</strong><p>선택한 조건은 등록된 도로 정보에 반영돼요. 시설 고장이나 미등록 턱까지 확인된 경로라는 뜻은 아니에요.</p></div></div>}
 <div className="survey-footer"><small>선택은 이 기기에 저장돼요.</small><div>{step>0&&<button onClick={()=>setStep(step-1)}>이전</button>}<button className="survey-next" onClick={()=>step<steps-1?setStep(step+1):onSave(draft)}>{coverage&&step===0?'내 조건 고르기':step<steps-1?'다음':'대전 둘러보기'} →</button></div></div></div><aside className="survey-art"><img src="/assets/survey/rest.webp" alt=""/><span>서두르지 않아도 괜찮아요</span><strong>갈 수 있는 길부터,<br/>가고 싶은 곳까지.</strong><p>나의 속도로 만나는 대전</p></aside></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
