import {useId,useState} from 'react';
import type {TransitSimulation} from './transit-types';
import {legSpan,transitPoint,transitStatus} from './transit-simulation';

const labels={walk:'보행',bus:'버스',subway:'지하철'} as const;
const icons={walk:'●',bus:'▣',subway:'▰'} as const;
export function TransitJourneyPlayer({simulation,playing,progress,speed,follow,onPlaying,onSeek,onSpeed,onFollow,onDetails}:{simulation:TransitSimulation;playing:boolean;progress:number;speed:number;follow:boolean;onPlaying:(v:boolean)=>void;onSeek:(v:number)=>void;onSpeed:(v:number)=>void;onFollow:(v:boolean)=>void;onDetails:()=>void}){
 const [collapsed,setCollapsed]=useState(true),detailsId=useId();const point=transitPoint(simulation,progress),current=point.segment,index=simulation.segments.indexOf(current),next=simulation.segments[index+1];
 const name=transitStatus(point);
 const toggle=()=>{if(progress>=1)onSeek(0);onPlaying(!playing);};
 return <div className={'journey-player transit-player mode-'+current.mode+(collapsed?' is-collapsed':'')}><div className="journey-heading"><span className="journey-live"/><strong>{progress>=1?'도착했어요 · 미리보기 완료':name+(playing?'':' · 일시정지')}</strong>{collapsed&&<><span className="journey-mini-progress">{Math.round(progress*100)}%</span><select className="journey-mini-speed" aria-label="시연 재생 속도" value={speed} onChange={e=>onSpeed(Number(e.target.value))}><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select><button className="journey-mini-follow" aria-pressed={follow} onClick={()=>onFollow(!follow)}>따라가기</button><button className="journey-mini-play" onClick={toggle} aria-label={playing?'시뮬레이션 일시정지':'시뮬레이션 재생'}>{playing?'Ⅱ':'▶'}</button></>}<button className="journey-collapse" aria-label={collapsed?"자세히 보기":"간단히 보기"} aria-expanded={!collapsed} aria-controls={detailsId} onClick={()=>setCollapsed(v=>!v)}>{collapsed?'⌃':'⌄'}</button></div><div id={detailsId} className="journey-expandable" inert={collapsed} aria-hidden={collapsed}><div className="journey-expandable-inner"><button className="journey-detail-link" onClick={onDetails}>경로 상세 ↗</button><div className="transit-now"><span>{icons[current.mode]}</span><div><b>{name}</b><small>{legSpan(current.start,current.end)} · 약 {progress>=1?0:Math.max(1,Math.round(current.minutes*(1-point.segmentProgress)))}분 남음</small></div>{next&&<em>다음 {labels[next.mode]}{next.line?' · '+next.line:''}</em>}</div><div className="transit-leg-strip" aria-label="환승 순서">{simulation.segments.map((s,i)=><button key={s.id} className={(s===current?'current ':'')+'mode-'+s.mode} onClick={()=>{onSeek(s.startProgress);onPlaying(false);}} aria-label={`${i+1}. ${labels[s.mode]} ${s.line}`}><span>{icons[s.mode]}</span><small>{s.mode==='walk'?'도보':s.line||labels[s.mode]}</small></button>)}</div><div className="journey-timeline"><input aria-label="대중교통 시뮬레이션 진행 위치" type="range" min="0" max="1000" value={Math.round(progress*1000)} onChange={e=>{onSeek(Number(e.target.value)/1000);onPlaying(false);}}/><div><span>{index+1}/{simulation.segments.length} 구간</span><b>{Math.round(progress*100)}%</b><span>약 {Math.round(simulation.totalMinutes)}분</span></div></div><div className="journey-controls"><button aria-label="처음으로" onClick={()=>{onSeek(0);onPlaying(false);}}>↺</button><button className="journey-play" onClick={toggle}>{playing?'Ⅱ 일시정지':progress>=1?'▶ 다시 보기':'▶ 시뮬레이션'}</button><select aria-label="시연 재생 속도" value={speed} onChange={e=>onSpeed(Number(e.target.value))}><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select><button aria-pressed={follow} onClick={()=>onFollow(!follow)}>따라가기 {follow?'켬':'끔'}</button></div><p>지하철은 지상에 투영해 보여주는 시연이에요. 실시간 차량 위치, 저상버스 배차와 엘리베이터 운영 상태를 뜻하지 않아요.</p></div></div></div>;
}
